#!/bin/bash
set -e
set -x

npm install --save webppl@latest webppl-timeit@latest webppl-dp@latest probmods/webppl-viz agentmodels/webppl-gridworld vega vega-lite
cd node_modules/vega
npm install
cd ../vega-lite
npm install
cd ../webppl
npm install
grunt compile:../webppl-timeit:../webppl-dp:../webppl-viz:../webppl-gridworld
cp compiled/webppl.min.js ../../assets/js/webppl.min.js
cd ../..
echo "Success."