#!/bin/bash
set -e
set -x

npm install --save probmods/webppl-editor
cd node_modules/wp-editor
npm install
make compiled/editor.js
cp compiled/editor.js ../../assets/js/webppl-editor.js
cp compiled/editor.css ../../assets/css/editor.css
cd ../..
echo "Success."